spring.application.name=smartdonation
spring.datasource.url=jdbc:mysql://localhost:3306/smartdonation?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Harshini@203
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=librarymanagement203@gmail.com
spring.mail.password=bwoglmqknzvjusge
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
# File upload directory
file.upload-dir=uploads/organizations

spring.security.user.name=disabled
spring.security.user.password=disabled
spring.web.resources.static-locations=classpath:/static/,file:./uploads/

